name: MLOps Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  # Setting an environment variable with the value of a configuration variable
  ECR_BACKEND_IMAGE: ${{ vars.ECR_BACKEND_IMAGE }}
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
  ECS_CLUSTER: ${{ vars.ECS_CLUSTER }}
  ECS_BACKEND_SERVICE: ${{ vars.ECS_BACKEND_SERVICE }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create .env file
      run: |
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
        echo "LLM_API_KEY=${{ secrets.LLM_API_KEY }}" >> .env
        echo "MODEL=${{ secrets.MODEL }}" >> .env
    - name: Run tests
      run: pytest

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create .env file
      run: |
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
        echo "LLM_API_KEY=${{ secrets.LLM_API_KEY }}" >> .env
        echo "MODEL=${{ secrets.MODEL }}" >> .env
        echo "PROJECT_NAME=${{ vars.PROJECT_NAME }}" >> .env
        echo "DESCRIPTION=${{ vars.DESCRIPTION }}" >> .env
        echo "VERSION=${{ vars.VERSION }}" >> .env

    - name: Set up QEMU for arm64
      run: |
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      if: runner.os == 'Linux'

    - name: Set up Docker for arm64
      uses: docker/setup-qemu-action@v2
      with:
        platforms: linux/arm64

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Set up Docker
      uses: docker/setup-buildx-action@v3
    - name: Build and push Docker image
      run: |
        docker buildx create --use
        docker buildx inspect --bootstrap
        docker buildx build --platform linux/arm64 -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_BACKEND_IMAGE:latest --push .
        docker buildx build --platform linux/arm64 -t cinex10/codinsight:latest --push .
    
    - name: Clean up .env
      run: rm .env