name: MLOps Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create .env file
      run: |
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
        echo "LLM_API_KEY=${{ secrets.LLM_API_KEY }}" >> .env
        echo "MODEL=${{ secrets.MODEL }}" >> .env
    - name: Run tests
      run: pytest

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create .env file
      run: |
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
        echo "LLM_API_KEY=${{ secrets.LLM_API_KEY }}" >> .env
        echo "MODEL=${{ secrets.MODEL }}" >> .env
        echo "API_V1_STR=${{ secrets.API_V1_STR }}" >> .env
        echo "PROJECT_NAME=${{ secrets.PROJECT_NAME }}" >> .env
        echo "DESCRIPTION=${{ secrets.DESCRIPTION }}" >> .env
        echo "VERSION=${{ secrets.VERSION }}" >> .env

    - name: Set up QEMU for arm64
      run: |
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      if: runner.os == 'Linux'

    - name: Set up Docker for arm64
      uses: docker/setup-qemu-action@v2
      with:
        platforms: linux/arm64

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3
    - name: Build Docker image
      run: |
        docker buildx create --use
        docker buildx inspect --bootstrap
        docker buildx build --platform linux/arm64 -t cinex10/codinsight:latest .
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Push Docker image
      run: |
        docker push cinex10/codinsight:latest
    - name: Clean up .env
      run: rm .env